# Generated by Django 3.2.9 on 2023-02-01 16:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('uploader', '0002_auto_20230201_2200'),
    ]

    operations = [
        migrations.RenameField(
            model_name='uploadfile',
            old_name='invoice_image',
            new_name='file',
        ),
    ]
